package com.gabrielnz.notificacao.entities;

public enum TipoDeNotificacao {
    AGENDAMENTO_PENDENTE,
    AGENDAMENTO_PENDENTE_ATUALIZADO,
    AGENDAMENTO_AGENDADO_ATUALIZADO,
    AGENDAMENTO_APROVADO,
    AGENDAMENTO_RECUSADO,
    AGENDAMENTO_AGENDADO_CANCELADO,
    CONFIRMAR_PRESENCA,
    AVISAR_FALTA
}
